### ISSUE TITLE
Depricated dependencies

### ISSUE THREAD

**Issue by set-killer** [google/identity-toolkit-node-client#11]
When I install this package I get the following warnings:

```
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated tap-consumer@0.0.1: This module is not supported. Please use 'tap' instead.
npm WARN installMany tap-consumer was bundled with tap@0.3.3, but bundled package wasn't found in unpacked tree
npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.
```

Is it possible to update to a newer version of `googleapis`? This package uses version 1.0.0, the newest one is 2.1.5

**Comment by ktkt1993** [comment]
I got the same errors. You should update the libraries.

**Comment by cryptoquick** [comment]
I got the same errors. You should update the libraries, Google...

**Comment by wyhao31** [comment]
Thanks for reporting the issue. Sorry for late reply.

All dependencies are updated now. Please use the latest version.

**Comment by set-killer** [comment]
Thank you :)

**Comment by cryptoquick** [comment]
Yep, thanks!
