### ISSUE TITLE
Cannot verify the key

### ISSUE THREAD

**Issue by hckhanh** [google/identity-toolkit-node-client#14]
It's very hard to use correctly at the first time, any product from Google.

I receive this error:

> Invalid token: Unable to verify the ID Token: Wrong recipient, payload audience != requiredAudience.

I follow the [Quick-start App for Node.js](https://developers.google.com/identity/toolkit/web/quickstart/nodejs#step_1_configure_the_google_identity_toolkit_api) to implement the demo application. I do it two time, but it does not work.

**Comment by wyhao31** [comment]
Sorry about the confusing.
Regarding your issue, how do you create GitkitClient object? Could you use the following way to create?

```
var gitkitClient = new GitkitClient(JSON.parse(fs.readFileSync('./gitkit-server-config.json')));
```

Actually, we use project id rather than client id as token's audience now. So, the README should be update. If you create GitkitClient object following the instruction in README. It should be like this:


```
  var gitkitClient = new GitkitClient({
    'clientId' : GOOGLE_OAUTH2_WEB_CLIENT_ID,
    'projectId' : PROJECT_ID_IN_DEVELOPER_CONSOLE,
    'serviceAccountEmail' : SERVICE_ACCOUNT_EMAIL@developer.gserviceaccount.com,
    'serviceAccountPrivateKeyFile' : PRIVATE_KEY_IN_PEM_FORMAT.pem,
    'widgetUrl' : 'http://localhost:8000/gitkit',
    'cookieName' : 'token'
  });
```

**Comment by hckhanh** [comment]
It's fine. I just wanna try tjis workflow. I will use another solution.
It's npt fit my requirement.

On 10:26AM, Mon, Apr 18, 2016 Yanhao Wang <notifications@github.com> wrote:

> Sorry about the confusing.
> Regarding your issue, how do you create GitkitClient object? Could you use
> the following way to create?
>
> var gitkitClient = new GitkitClient(JSON.parse(fs.readFileSync('./gitkit-server-config.json')));
>
> Actually, we use project id rather than client id as token's audience now.
> So, the README should be update. If you create GitkitClient object
> following the instruction in README. It should be like this:
>
>   var gitkitClient = new GitkitClient({
>     'clientId' : GOOGLE_OAUTH2_WEB_CLIENT_ID,
>     'projectId' : PROJECT_ID_IN_DEVELOPER_CONSOLE,
>     'serviceAccountEmail' : SERVICE_ACCOUNT_EMAIL@developer.gserviceaccount.com,
>     'serviceAccountPrivateKeyFile' : PRIVATE_KEY_IN_PEM_FORMAT.pem,
>     'widgetUrl' : 'http://localhost:8000/gitkit',
>     'cookieName' : 'token'
>   });
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>
-- 
Yours sincerely,
Khanh Hoang
