### ISSUE TITLE
Are Service Account Email and Private Key File necessary?

### ISSUE THREAD

**Issue by zackharley** [google/identity-toolkit-node-client#18]
I'm using the identity toolkit to verify tokens, but I've removed the `serviceAccountEmail` and `serviceAccountPrivateKeyFile` fields in my `gitkit.server.config.js` file and the identity toolkit sign in still works. Do I actual need to include the `serviceAccountEmail` and `serviceAccountPrivateKeyFile` fields?

This is my `gitkit.server.config.js`:

```
const widgetHost = process.env.APP_HOST || 'localhost:8000';

let config = {
  clientId: '*************',
  projectId: '***********',
  widgetUrl: `http://${widgetHost}/gitkit`,
  cookieName: 'gtoken'
};

export default config;
```

**Comment by wyhao31** [comment]
Hi Zack,

If you only need to verify tokens, service account email and private key are not required. These service account info are only needed when you want to do something using service account, such as downloading all your users' accounts.

Thanks.

**Comment by zackharley** [comment]
Great to know! Thanks a ton
